### ISSUE TITLE
model.predict_generator has a bug. 

### ISSUE THREAD

**Issue by lindameiguo** [GRAAL-Research/pytoune#9]
# It doesn't work! It transforms a given data_loader to list type and hence models can't predict.

model.fit_generator(train_loader, valid_loader, epochs=args.EPOCH, callbacks=callbacks)
model.predict_generator(train_loader)
Epoch 1/1 8.06s Step 11/11: loss: 2.622029, acc: 22.405432, val_loss: 2.358737, val_acc: 35.961538
Epoch 1: val_acc improved from -inf to 35.96154, saving model to best_epoch_1.ckpt
Restoring model from best_epoch_1.ckpt

Traceback (most recent call last):
  File "c:/Users/Administrator/excise.py", line 138, in <module>
    model.predict_generator(train_loader)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pytoune\framework\model.py", line 397, in predict_generator
    pred_y.append(torch_to_numpy(self.model(x)))
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\Users\Administrator\d.py", line 260, in forward
    out = self.conv1(x)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 421, in forward
    self.padding, self.dilation, self.groups)
TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not list'

**Comment by freud14** [comment]
Hi, the generator taken by `predict_generator` must yield a batch of examples without their labels, not a tuple (or list) as your `train_loader` does. Instead, I suggest that you use the `evaluate_generator` method which returns your loss, your metrics (if any) and can return predictions as follows.
```python
model.fit_generator(train_loader, valid_loader, epochs=args.EPOCH, callbacks=callbacks)
loss, metrics, y_pred_batches = model.evaluate_generator(train_loader, return_pred=True)
y_pred = np.concatenate(y_pred_batches)
```
Since the *_generator methods do not assume the return type of your network, you must concatenate them manually as is shown above.

However, since you want predictions on your `train_loader`, beware of the fact that the examples might be shuffled (if you used shuffle=True in your DataLoader init) and thus you would not be able to associate the predictions with their examples. To do so, the current `dev` branch of PyToune offers a `predict_on_batch` method which can be used the following way:
```python
model.fit_generator(train_loader, valid_loader, epochs=args.EPOCH, callbacks=callbacks)
y_pred_batches = []
for x, y in train_loader:
    y_pred_batch = model.predict_on_batch(x)
    y_pred_batches.append(y_pred_batch)
y_pred = np.concatenate(y_pred_batches)
```
However, this is not available in the current "pip" version of PyToune. To install this version, you have to clone the repo and install PyToune manually with the following command lines.
```sh
git clone https://github.com/GRAAL-Research/pytoune.git
cd pytoune
git checkout dev
python setup.py install
```

I hope that this can help with your problem.

Thank you.

Frédérik

**Comment by lindameiguo** [comment]
@freud14 
Thank you.  Since i just need the trained network to return y_pred on a test set, i find the following code can solve my problem.
`pred = model.predict(test_data.to(device), batch_size = 100)`
